import pandas as pd

df = pd.read_csv("data_1.csv")

# BASE CALCULATIONS

df["Net Profit"] = df["Revenue"] - df["Expenses"]

previous_revenue = df["Revenue"].shift(1)
previous_expenses = df["Expenses"].shift(1)
df["Expense Growth Pecentage"] = (
    (df["Expenses"] - previous_expenses) / previous_expenses * 100
)

# FINANCIAL FROWTH

df ["Revenue Growth Percentage"] = (
    (df["Revenue"] - previous_revenue) / previous_revenue * 100
)

df["Revenue per Dollar Expense"] = (
    df["Revenue"] / df["Expenses"]
)

df["Net Profit Margin"] = (
    df["Net Profit"] / df["Revenue"]
) * 100

#FINANCIAL HEALTH

df["Current Ratio"] = (
    df["CurrentAssets"] / df["CurrentLiabilities"]
)

df["Debt to Asset Ratio"] = (
    df["Debt"] / df["Assets"]
) * 100

df["Revenue-Expense Growth Differential"] = (
    df["Revenue Growth Percentage"]
    - df["Expense Growth Pecentage"]
)

#CUSTOMER HEALTH

df["Revenue per Customer"] = (
    df["Revenue"] / df["TotalCustomers"]
)

df["Purchases per Customer"] = (
    df["Orders/Purchases"] / df["TotalCustomers"]
)

df["Profit per Customer"] = (
    df["Net Profit"] / df["TotalCustomers"]
)

#MARKETING EFFICIENCY

df["Revenue per Marketing Dollar"] = (
    df["Revenue"] / df["MarketingSpend"]
)

df["Marketing Spend as % of Revenue"] = (
    df["MarketingSpend"] / df["Revenue"]
) * 100

df["Marketing Spend per Order"] = (
    df["MarketingSpend"] / df["Orders/Purchases"]
)

#OPERATIONAL EFFICIENCY

df["Revenue per Employee"] = (
    df["Revenue"] / df["NumberOfEmployees"]
)

df["Orders per Employee"] = (
    df["Orders/Purchases"] / df["NumberOfEmployees"]
)

df["Revenue per Labour Hour"] = (
    df["Revenue"] / df["LabourHours"]
)

df = df.round(2)

def eval_revenue_growth(value):
    if value > 0:
        return (
            "Healthy",
            f"Revenue increased by {value:.1f}% compared with the previous period."
        )

    elif value < 0:
        return (
            "Needs Improvement",
            f"Revenue decreased by {abs(value):.1f}% compared with the previous period."
        )

    else:
        return (
            "Stable",
            "Revenue did not change compared with the previous period."
        )


latest_growth = df["Revenue Growth Percentage"].iloc[-1]

status, reason = eval_revenue_growth(latest_growth)

print("\nREVENUE GROWTH ANALYSIS")
print("Status:", status)
print("Reason:", reason)

# Explanations of each metric

metric_explanations = {
    "Revenue Growth (%)":
        "Measures how quickly revenue is increasing or decreasing.",

    "Revenue per Dollar Expense":
        "Shows how much revenue the business generates for every $1 of expense.",

    "Net Profit Margin (%)":
        "Shows what percentage of revenue remaining as actual profit after expenses.",

    "Current Ratio":
        "Measures whether current assets (assets converted into cash within a year are sufficient to cover current liabilities (liabilities due within a year).",

    "Debt to Asset Ratio (%)":
        "Shows how much of the company's assets are financed through debt.",

    "Revenue-Expense Growth Differential":
        "Compares revenue growth with expense growth to see how sustainable growth is",

    "Revenue per Customer":
        "Shows the average revenue generated by each customer.",

    "Purchases per Customer":
        "Shows how many purchases the average customer makes.",

    "Profit per Customer":
        "Shows the average profit generated per customer.",

    "Revenue per Marketing Dollar":
        "Shows how total revenue for every $1 spent on marketing.",

    "Marketing Spend as Percentage of Revenue":
        "Shows how much of revenue is represented by marketing spending.",

    "Marketing Spend per Order":
        "Shows how much marketing spend per order.",

    "Revenue per Employee":
        "Shows how much revenue the average employee supports.",

    "Orders per Employee":
        "Shows how many orders the average employee supports.",

    "Revenue per Labour Hour":
        "Shows how much revenue is generated for every labour hour."
}